name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH_Base: 'src\Probabilistic.Structures\Probabilistic.Structures.csproj'
  PROJECTTEST_PATH_Base: 'tests\Probabilistic.Structures.Tests\Probabilistic.Structures.Tests.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet 5'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Install dotnet 6'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Install dotnet 7'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH_Base }}     
      
    - name: 'Test project'
      run: dotnet test ${{ env.PROJECTTEST_PATH_Base }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH_Base }} --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version-without-v }}

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH_Base }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
    - name: 'Push packages'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.symbols.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}